### ISSUE TITLE
Feature: Refactor Callbackwrappers

### ISSUE THREAD

**Issue by MohnJcAfee** [ArchitektApx/GalaxyViewPlus#1]
Callbackwrappers are a static fugly hellhole currently -> refactor to be at least a little better

- [x] rewrite callbackwrappers and factory
- [x] rewrite implementation in classes that use the factory
- [x] rewrite tests
- [x] merge from featurebranch to dev
- [x] merge from dev to master

**Comment by MohnJcAfee** [comment]
> rewrite callbackwrappers and factory
Done in c03ae3a48ae6f967129e26100c0460989e04e071

**Comment by MohnJcAfee** [comment]
> rewrite callbackwrappers and factory

Done in b67f74fc84b7eb3a5a58b39311f8255a2a278ce3

> rewrite implementation in classes that use the factory 

Done in c42658c6ac7368ce013ec109311594d1cc62b044

>  rewrite tests

Done in b67f74fc84b7eb3a5a58b39311f8255a2a278ce3

**Comment by MohnJcAfee** [comment]
- [X] Tests worked
- [X] 100% coverage
- [x] Merged into Dev in  6db83ff13f498876744d2dae3a6393396c53e6a8

**Comment by ArchitektApx** [comment]
Merged and released as 1.3.0 in 2cd2eaba880528e9bdd2b272909756569488f659
