### ISSUE TITLE
Feature: Refactor userinterface HTML element creation

### ISSUE THREAD

**Issue by MohnJcAfee** [ArchitektApx/GalaxyViewPlus#2]
The userinterface elements, especially the factories for html elements can be cut down massively to reduce code reuse.

- [x] refactor/simplify HTML elements and factories
- [x] refactor tests
- [x] merge to dev
- [x] merge to master

**Comment by ArchitektApx** [comment]
merged to master with 1.4.1 c48234052c8e0b73982487f38d5bb4a08f69e678
